vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        project:
            uri_prefix:         '%app.path.images%'
            upload_destination: '%kernel.project_dir%/public%app.path.images%'
        skill:
            uri_prefix:         '%app.path.images%'
            upload_destination: '%kernel.project_dir%/public%app.path.images%'
